{{- if .Values.secretEnvVariables }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fast-api-demo.fullname" . }}
  labels:
    {{- include "fast-api-demo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.secretEnvVariables }}
    {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
